version: 2
updates:
  # Update Python dependencies in requirements.txt
  - package-ecosystem: "pip"
    directory: "/requirements" # Location of the requirements.txt file
    schedule:
      interval: "weekly" # Checks for updates every week
    commit-message:
      prefix: "fix(deps)" # Customize commit message prefix
    open-pull-requests-limit: 5 # Limits the number of open PRs

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "daily" # Checks for updates daily
