---
language_version: python3.12
repos:
  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0 # Replace with the latest stable version
    hooks:
      - id: black

  # Flake8 for Python code linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Replace with the latest stable version
    hooks:
      - id: flake8
        args:
          - --max-line-length=88  # Customize as needed
          - --ignore=E402  # Example of ignoring a specific rule

  # Pylint for advanced Python linting
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1 # Replace with the latest stable version
    hooks:
      - id: pylint
        args: ["--disable=E0401,R0903,W0613,W0621,C0413"]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0  # Replace with the latest stable version
    hooks:
      - id: hadolint


  # Detect secrets (to avoid committing sensitive information)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0  # Replace with the latest stable version
    hooks:
      - id: detect-secrets
