version: "3.9"
services:
  api:
    build: .
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /app/src/
        - action: rebuild
          path: requirements/dev.txt

    image: fastapiapp:latest
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: .
        target: /app/
    depends_on:
      - db
    environment: 
        - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}



  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB


volumes:
  postgres_data:
    driver: local