{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
data:
  {{- range $key, $val := .data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end }}