apiVersion: v1
kind: Secret
metadata:
    name: {{ include "fast-api-kube.fullname" . }}-registry-key-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
