apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fast-api-kube.fullname" . }}
  labels:
    {{- include "fast-api-kube.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
