apiVersion: v1
kind: Secret
metadata:
  # The name of the secret is derived from a helper template, maintaining naming consistency.
  name: {{ include "fast-api-kube.fullname" . }}-secrets

type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  
  