apiVersion: v1
kind: Secret
metadata:
  # The name of the secret is derived from a helper template, maintaining naming consistency.
  name: "db-password"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Encode the database password from values.yaml as a base64 string for security.
  db-password: {{ .Values.db.password | b64enc }}