apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-api-kube.fullname" . }}
  labels:
    {{- include "fast-api-kube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port  | default 30000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fast-api-kube.selectorLabels" . | nindent 4 }}
