"""generate base

Revision ID: d45e71dabb1c
Revises: 
Create Date: 2024-09-25 16:08:53.863417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45e71dabb1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_log',
    sa.Column('queryID', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('queryID')
    )
    op.create_index(op.f('ix_query_log_queryID'), 'query_log', ['queryID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_log_queryID'), table_name='query_log')
    op.drop_table('query_log')
    # ### end Alembic commands ###
