name: FastAPI Tests

on: 
  push:
    branches: [ "main","dev","stagging" ]
  pull_request:
    branches: [ "main" , "dev","stagging" ]
jobs:

  flake8:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.9
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.9
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-html
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        mkdir -p reports/flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --format=html --htmldir=reports/flake8
    - name: Archive flake8 coverage results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: flake8-coverage-report
        path: reports/flake8/

  pytest:
    name: Unit Testing
    needs: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.9
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.8
    - name: Install depen9encies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/staging.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-html pytest-sugar pytest-json-report
        pytest -v --cov --html=reports/pytest/report.html
    - name: Archive pytest coverage results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: pytest-coverage-report
        path: reports/pytest/

  security_checks:
    needs: pytest
    runs-on: ubuntu-latest
    name: Security check
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@v1.25.1
        with:
          path: src/